---
title: "Project Proposal"
author: "Madison Mendez"
date: "1/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#For my capstone project, I will predict whether a person's income is over or under $50k/year based on various characteristics. From there, I will assess the validity of the model. 

#I will be analyzing a "Census Income Data Set" from the UCI Machine Learning Repository for this project. The dataset can be found here: http://mlr.cs.umass.edu/ml/datasets/Census+Income

#Based on my analysis, people entering the workforce will be able to calculate which income bracket they can expect to be in. A person will be able to decide how to help themselves earn more money by pursuing a further education level or choosing a different profession.


#I will use chi-squared tests to determine which variables are relevant for my analysis. After eliminating the variables that are unnecessary, I will use regression techniques to determine the effects of the remaining variables on a person's expected income bracket. I will present the conclusion of my project with code and a final paper. 

#Citation:
# @misc{Asuncion+Newman:2007 ,
# author = "A. Asuncion and D.J. Newman",
# year = "2007",
# title = "{UCI} Machine Learning Repository",
# url = "http://www.ics.uci.edu/$\sim$mlearn/{MLR}epository.html",
# institution = "University of California, Irvine, School of Information and Computer Sciences" }
```

